base_url = "https://ukint-vs.github.io"
title = "~/ukint-vs"
description = ""
author = "ukint-vs"
generate_feed = true
compile_sass = true
minify_html = true
default_language = "en"

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
external_links_target_blank = true
highlight_code = true
highlight_theme = "css"

highlight_themes_css = [
  { theme = "ayu-dark", filename = "syntax-dark.css" },
  { theme = "ayu-light", filename = "syntax-light.css" },
]

[extra]

# Enable JavaScript theme toggler for dark/light mode (and automatic switching).
# The default setting is the light theme.
theme_switcher = true

# Add a "copy" button to codeblocks (loads ~700 bytes of JavaScript).
copy_button = true

# Date format used when listing posts (main page, /blog section, tag posts list…)
# Default is "6th July 2049" in English and "%d %B %Y" in other languages.
long_date_format = "%d %B %Y"

# Date format used for blog posts.
# Default is "31st Dec 2011".
short_date_format = ""

# Custom separator used in title tag and posts metadata (between date, time to read, and tags).
separator = "•"

# Full path after the base URL required. So if you were to place it in "static" it would be "/favicon.ico"
favicon = "/img/favicon.ico"

# Add an emoji here to use it as favicon.
# Compatibility: https://caniuse.com/link-icon-svg
# favicon_emoji = "🌱"

# This header image is used for SEO. For example if you were to share an image via Messenger/Instagram/Twitter a preview picture is also presented
headerImage = ""

menu = [
    { name = "blog", url = "blog/" },
    { name = "archive", url = "archive/" },
    { name = "tags", url = "tags/" },
    # { name = "projects", url = "projects/" },
]

# The RSS icon will be shown if (1) it's enabled and (2) the following variable is set to true.
feed_icon = true

# The icons available can be found in "social_icons" in the "static" folder.
socials = [
    { name = "github", url = "https://github.com/ukint-vs/", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/vadim-smirnov-b03853216/", icon = "linkedin" },
]

# Custom security headers. What urls should your website be able to connect to?
# You need to specify the CSP and the URLs associated with the directive.
# Useful if you want to load remote content safely (embed YouTube videos, which needs frame-src, for example).
# Default directive is self.
# Default config, allows for https remote images and embedding YouTube and Vimeo content.
# This configuration (along with the right webserver settings) gets an A+ in Mozilla's Observatory: https://observatory.mozilla.org
allowed_domains = [
    { directive = "font-src", domains = ["'self'", "data:", "fonts.gstatic.com"] },
    { directive = "img-src", domains = ["'self'", "https://*", "data:"] },
    { directive = "script-src", domains = ["'self'"] },
    { directive = "style-src", domains = ["'self'", "fonts.googleapis.com"] },
    { directive = "frame-src", domains = ["player.vimeo.com", "https://www.youtube-nocookie.com"] },
]


# Custom subset of characters for the header.
# If set to true, the `static/custom_subset.css` file will be loaded first.
# This avoids a flashing text issue in Firefox.
# Please see https://welpo.github.io/tabi/blog/custom-font-subset/ to learn how to create this file.
custom_subset = true

# giscus support for comments. https://giscus.app
# Setup instructions: https://welpo.github.io/tabi/blog/comments/#setup
[extra.giscus]
enabled_for_all_posts = false  # Enables giscus on all posts. It can be enabled on individual posts by setting `giscus = true` in the [extra] section of a post's front matter.
automatic_loading = true  # If set to false, a "Load comments" button will be shown.
repo = "ukint-vs/ukint-vs.github.io"
repo_id = "MDEwOlJlcG9zaXRvcnkzNDkzMjI1Nzc="  # Find this value in https://giscus.app/
category = "Announcements"
category_id = "DIC_kwDOFNI9Uc4CYOUr"  # Find this value in https://giscus.app/
mapping = "slug"  # Available: pathname; url; title; slug. "slug" will use the post's filename (slug); this is the only way to share comments between languages.
strict_title_matching = 1  # 1 to enable, 0 to disable. https://github.com/giscus/giscus/blob/main/ADVANCED-USAGE.md#data-strict
enable_reactions = 1  # 1 to enable, 0 to disable.
comment_box_above_comments = true
light_theme = "noborder_light"
dark_theme = "noborder_dark"
lang = ""  # Leave blank to match the page's language.
lazy_loading = true
